*** Settings ***
Variables  ../../resources/test_data/python_data/data.py
*** Variables ***

# Exported text data that is generated by faker library and all used data in test

${root_dir}=  ${CURDIR}..${/}..${/}..${/}
${default_export_test_data}=  ${root_dir}results${/}exported_test_data${/}
${create_offer_export_test_data}=  ${root_dir}results${/}exported_test_data${/}offer_desk${/}${create_offer_td_file}
${ems_export_test_data}=  results${/}exported_test_data${/}offer_desk${/}